version: "3"
services:
  postgresql:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
